name: Build Coffee Hub Android APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x coffee-hub-android/gradlew

      - name: Build APK
        run: |
          cd coffee-hub-android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CoffeeHub-APK
          path: coffee-hub-android/app/build/outputs/apk/release/*.apk