name: Build Coffee Hub Android APK

on:
  push:
    branches:
      - main
    paths:
      - 'coffee-hub-android/**'
      - '.github/workflows/build-android.yml'

  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradle
        run: chmod +x coffee-hub-android/gradlew

      - name: Build Android APK
        run: |
          cd coffee-hub-android
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoffeeHub-APK
          path: coffee-hub-android/app/build/outputs/apk/release/*.apk